name: CI/CD

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:

  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
    # install dependencies
    - run: npm ci
    # start the server and run tests
    - name: Start server
      run: npm start&
      continue-on-error: true
    - name: Wait for server to start
      run: |
        timeout=300 # Timeout in seconds
        end=$((SECONDS+$timeout))
        until npm run check-server; do
          if [[ $SECONDS -ge $end ]]; then
            echo "Failed to start server within $timeout seconds."
            exit 1
          fi
          echo "Waiting for server to start..."
          sleep 5
        done
    # end to end
    - run: npm run test:e2e
    # unit tests
    - run: npm run test:unit
    # integration tests
    - run: npm run test:int

  build-and-deploy:
    needs: test
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
    - run: npm ci
    - run: npm run build
    - name: Deploy to GitHub Pages
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        branch: gh-pages
        folder: dist
